### ISSUE TITLE
Dim lights at night

### ISSUE THREAD

**Issue by soffes** [soffes/home#10]
All lights should dim and go towards a redish tint when the sun starts setting and vice versa. 

There are a few exceptions:

- outdoor lights
- if party mode is on
- guest bedroom

This will likely require automations for all switches and an automation that runs in a timer loop every ~10 minutes to change to the next tick in the gradient.

**Comment by adamawolf** [comment]
🎉

**Comment by soffes** [comment]
I'm planning to implement this with [AppDaemon](https://www.home-assistant.io/docs/ecosystem/appdaemon/). I set it up via its Hass.io addon and did some basic configuration in 799da9da4844b39ccd0bc75f81129795f08171a0. I think this will be a great solution for lights that react to the time of day gradient :)
