### ISSUE TITLE
Send reminders to take out the trash unless vacation mode is on

### ISSUE THREAD

**Issue by soffes** [soffes/home#12]
I keep forgetting.

It would be great too if it send it at ~8pm the night before and then again when arriving home if I wasn't at home when it originally sent.

**Comment by teich** [comment]
Maybe stick a [Aqara vibration sensor ](https://smile.amazon.com/Aqara-Vibration-Sensor-Automation-Compatible/dp/B07PJT939B/ref=sr_1_2?keywords=aqara+vibration+sensor&qid=1579631826&sr=8-2) to detect if you've moved them and disable or escalate notifications appropriately.

**Comment by soffes** [comment]
@teich good idea! I was thinking about a laser or something to detect if they were there. Vibration sensor might be easier!
