### ISSUE TITLE
Custom Alarm

### ISSUE THREAD

**Issue by soffes** [soffes/home#27]
Look into setting up a [manual alarm system](https://www.home-assistant.io/integrations/manual/)

**Comment by jnpetersen** [comment]
Hey, I came across your github, and I like seeing other in the community putting their code out here.  I've actually used a NodeMCU hooked up to the reed switches my alarm panel used to use, so I can actually monitor and create automations around it.  I have my code going to my own gitlab repository, but I'll be cleaning it up and putting it on GitHub soon.

If you are interested, let me know.

**Comment by soffes** [comment]
Neat! Thanks!

Haven't made time for much stuff like this lately. Next time I'm on this, I'll check out your repo :)

**Comment by CCOSTAN** [comment]
I did this with NodeMCUs.. it was great. 
https://www.vcloudinfo.com/2017/06/building-my-home-alarm-system-hardware.html
